const FOOD=[
['tea','☕ Tea · 250 ml',100,4,4,10],
['chap','🫓 Chapathi · 1 piece',120,4,3,20],
['chicken','🍗 Chicken curry · 1 serving',220,30,10,2],
['chick','🫘 Chickpea curry · 1 bowl',220,10,6,30],
['egg','🥚 Egg · 1',70,6,5,0.5],
['peanut','🥜 Peanuts · 25 g',145,6,12,5],
['pump','🎃 Pumpkin seeds · 25 g',140,7,12,4],
['banana','🍌 Banana · 1 medium',105,1,0,27],
['curd','🥣 Curd · 150 g',90,5,4,7],
['rice','🍚 Cooked white rice · 1 cup',205,4,0.5,45],
['matta','🍚 Kerala matta rice · 1 cup',215,5,1.5,45],
['dosa','🥞 Dosa · 1 medium',130,3,3,22],
['idli','⚪ Idli · 2',120,4,1,25],
['puttu','🥥 Puttu · 1 medium serving',220,5,4,40],
['appam','🥞 Appam · 1',120,2,2,24],
['parotta','🫓 Kerala parotta · 1',220,4,9,30],
['idiyappam','🍜 Idiyappam · 2',150,3,1,32],
['sambar','🥣 Sambar · 1 cup',120,6,3,17],
['avial','🥕 Avial · 1 cup',170,4,10,16],
['thoran','🥬 Vegetable thoran · 1 cup',150,3,9,14],
['fishcurry','🐟 Kerala fish curry · 1 serving',180,23,8,5],
['sardine','🐟 Sardine / mathi · 2 medium pieces',190,22,10,1],
['beef','🥩 Kerala beef curry · 1 serving',300,27,20,3],
['chickenb','🍗 Chicken biryani · 1 plate',650,30,22,75],
['vegb','🍛 Vegetable biryani · 1 plate',480,10,14,70],
['beefb','🥩 Beef biryani · 1 plate',700,30,28,75],
['pazham','🍌 Pazham pori · 1 piece',180,2,8,28],
['tea2','☕ Black tea with sugar · 250 ml',70,0,0,18],
['coffee','☕ Coffee with milk & sugar · 250 ml',110,4,4,14]
]
const TEST=[['pull','🏋️ Pull-ups','reps',10],['push','💪 Push-ups','reps',18],['plank','🧱 Plank','sec',60],['leg','🦵 Lying leg raises','reps',12],['hang','🔗 Hanging knee raises','reps',8],['roller','🛞 Ab roller','reps',4],['side','↔️ Side plank','sec/side',30],['squat','🦵 Squats','reps',30]];
const DEFAULT={age:29,activity:1.35,deficit:400,targets:{cal:1700,p:120,f:55,c:185},cal:0,p:0,f:0,c:0,meals:[],steps:0,cycle:0,burn:0,workout:false,tests:{pull:10,push:18,plank:60,leg:12,hang:8,roller:4,side:30,squat:30},daily:[],weights:[68],measure:[{day:0,w:68,b:97,z:90,ch:100,arm:30}]};
let s={...DEFAULT,targets:{...DEFAULT.targets},tests:{...DEFAULT.tests},meals:[],daily:[],weights:[68],measure:[{...DEFAULT.measure[0]}]};
let currentUser=null, todayLogId=null;
const CACHE='flc-v3-3';
const localKey=()=>`${CACHE}:${currentUser?.id||'guest'}`;
function saveLocal(){try{localStorage.setItem(localKey(),JSON.stringify(s))}catch(e){}}
function loadLocal(){try{const x=localStorage.getItem(localKey());if(x)s={...s,...JSON.parse(x)}}catch(e){}}
function save(){saveLocal()}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dayNum(){return Math.max(0,s.daily.length)}
async function dbProfile(){if(!currentUser)return;const {data,error}=await supabaseClient.from('profiles').select('*').eq('id',currentUser.id).maybeSingle();if(error){console.error(error);return}if(data){s.age=data.age||s.age;s.activity=Number(data.activity_level)||s.activity;s.deficit=data.deficit_kcal||s.deficit;s.targets={cal:data.calorie_target||s.targets.cal,p:data.protein_target||s.targets.p,f:data.fat_target||s.targets.f,c:data.carb_target||s.targets.c};s.tests={...s.tests,...(data.baseline||{})}}}
async function ensureProfile(){if(!currentUser)return;await supabaseClient.from('profiles').upsert({id:currentUser.id,age:s.age,sex:'male',height_cm:159,starting_weight_kg:68,activity_level:s.activity,deficit_kcal:s.deficit,calorie_target:s.targets.cal,protein_target:s.targets.p,fat_target:s.targets.f,carb_target:s.targets.c,baseline:s.tests},{onConflict:'id'})}
async function loadCloud(){if(!currentUser)return;await dbProfile();const {data:logs,error}=await supabaseClient.from('daily_logs').select('*').eq('user_id',currentUser.id).order('log_date',{ascending:true}).limit(180);if(error){toast('Cloud read failed: '+error.message);return}s.daily=(logs||[]).map(x=>({day:x.day_number||0,cal:x.calories||0,p:x.protein||0,f:x.fat||0,c:x.carbs||0,burn:x.exercise_calories||0,steps:x.steps||0,weight:x.weight_kg}));const {data:ms}=await supabaseClient.from('body_measurements').select('*').eq('user_id',currentUser.id).order('measure_date',{ascending:true});if(ms?.length)s.measure=ms.map(x=>({day:x.day_number||0,w:x.weight_kg,b:x.belly_cm,z:x.waist_cm,ch:x.chest_cm,arm:x.biceps_cm}));const {data:todayRow}=await supabaseClient.from('daily_logs').select('*').eq('user_id',currentUser.id).eq('log_date',today()).maybeSingle();if(todayRow){todayLogId=todayRow.id;s.cal=todayRow.calories||0;s.p=todayRow.protein||0;s.f=todayRow.fat||0;s.c=todayRow.carbs||0;s.steps=todayRow.steps||0;s.cycle=todayRow.cycling_minutes||0;s.burn=todayRow.exercise_calories||0;s.workout=!!todayRow.workout_completed;s.weights=[...(s.weights||[]),...(todayRow.weight_kg?[todayRow.weight_kg]:[])];const {data:meals}=await supabaseClient.from('meals').select('*').eq('daily_log_id',todayRow.id).order('created_at',{ascending:true});s.meals=(meals||[]).map(x=>[x.food_key||'custom',x.food_name,x.calories,x.protein,x.fat,x.carbs])}saveLocal()}
async function cloudDaily(){if(!currentUser)return;const payload={user_id:currentUser.id,log_date:today(),day_number:dayNum(),calories:Math.round(s.cal),protein:Math.round(s.p),fat:Math.round(s.f),carbs:Math.round(s.c),exercise_calories:Math.round(s.burn),steps:Math.round(s.steps),walking_minutes:Math.round(s.steps/100),cycling_minutes:Math.round(s.cycle),workout_completed:s.workout,weight_kg:s.weights.at(-1)||null};const {data,error}=await supabaseClient.from('daily_logs').upsert(payload,{onConflict:'user_id,log_date'}).select().single();if(error){toast('Cloud save failed: '+error.message);return}todayLogId=data.id}
async function cloudMeal(x){if(!currentUser)return;if(!todayLogId)await cloudDaily();const {error}=await supabaseClient.from('meals').insert({user_id:currentUser.id,daily_log_id:todayLogId,meal_type:'food',food_key:x[0],food_name:x[1],quantity:1,unit:'serving',calories:x[2],protein:x[3],fat:x[4],carbs:x[5]});if(error)toast('Meal save failed: '+error.message)}
async function sync(){saveLocal();if(currentUser){await cloudDaily();}}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.p===id));render()}
function modal(id){document.getElementById(id).classList.add('show');if(id==='profile'){age.value=s.age;activity.value=s.activity;deficit.value=s.deficit}if(id==='account'){authStatus.textContent=currentUser?`Signed in as ${currentUser.email}`:'Not signed in. Sign in to sync across devices.'}}
function closeM(){document.querySelectorAll('.modal').forEach(x=>x.classList.remove('show'))}
function toast(t){let x=document.getElementById('toast');x.textContent=t;x.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.remove('show'),2400)}
async function signUpUser(){const email=authEmail.value.trim(),password=authPassword.value;if(!email||password.length<6)return toast('Enter an email and 6+ character password');const {data,error}=await supabaseClient.auth.signUp({email,password});if(error)return toast(error.message);if(data.session){currentUser=data.user;await ensureProfile();await loadCloud();closeM();render();toast('Cloud account created')}else toast('Check your email to confirm your account.')}
async function signInUser(){const email=authEmail.value.trim(),password=authPassword.value;const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)return toast(error.message);currentUser=data.user;await ensureProfile();await loadCloud();closeM();render();toast('Cloud sync enabled')}
async function signOutUser(){await supabaseClient.auth.signOut();currentUser=null;todayLogId=null;s={...DEFAULT,targets:{...DEFAULT.targets},tests:{...DEFAULT.tests},meals:[],daily:[],weights:[68],measure:[{...DEFAULT.measure[0]}]};closeM();render();toast('Signed out')}
async function saveProfile(){s.age=+age.value;s.activity=+activity.value;s.deficit=+deficit.value;let bmr=10*68+6.25*159-5*s.age+5,tdee=bmr*s.activity;let cal=Math.max(1400,Math.round(tdee-s.deficit));let p=120,f=55,c=Math.round((cal-p*4-f*9)/4);s.targets={cal,p,f,c};save();if(currentUser)await ensureProfile();closeM();render();toast(`${cal} kcal · ${p} g protein target`)}
function add(id){let x=FOOD.find(x=>x[0]===id);s.cal+=x[2];s.p+=x[3];s.f+=x[4];s.c+=x[5];s.meals.push(x);save();cloudMeal(x);sync();render();toast(x[1]+' added')}
function customFood(){let x=['custom','🍽️ '+fn.value,+fc.value||0,+fp.value||0,+ff.value||0,+fcarb.value||0];s.cal+=x[2];s.p+=x[3];s.f+=x[4];s.c+=x[5];s.meals.push(x);save();cloudMeal(x);sync();closeM();render();toast('Food added')}
async function clearToday(){if(currentUser&&todayLogId)await supabaseClient.from('meals').delete().eq('daily_log_id',todayLogId);s.cal=0;s.p=0;s.f=0;s.c=0;s.meals=[];save();await sync();render()}
function renderFoodList(query=''){const q=query.trim().toLowerCase();const list=FOOD.filter(x=>!q||x[1].toLowerCase().includes(q));document.getElementById('foods').innerHTML=list.length?list.map(x=>`<button onclick="add('${x[0]}')">${x[1]}<b>~${x[2]} kcal</b></button>`).join(''):'<div class="card">No matching food. Use “Add custom food” below.</div>'}
async function steps(v){s.steps=+v;save();await sync();render()}
async function saveWeight(){let w=+nw.value;s.weights.push(w);save();await sync();closeM();render();toast('Weight saved')}
async function saveMeasure(){let m={day:s.measure.length*7,w:+mw.value,b:+mb.value,z:+mz.value,ch:+mc.value,arm:+marm.value};s.measure.push(m);s.weights.push(m.w);save();if(currentUser){const {error}=await supabaseClient.from('body_measurements').insert({user_id:currentUser.id,measure_date:today(),day_number:m.day,weight_kg:m.w,belly_cm:m.b,waist_cm:m.z,chest_cm:m.ch,biceps_cm:m.arm});if(error)toast('Measurement save failed: '+error.message)}await sync();closeM();render();toast('Measurements saved')}
function changeTest(id,delta){s.tests[id]=Math.max(0,(s.tests[id]||0)+delta);const el=document.getElementById('v_'+id);if(el)el.textContent=s.tests[id]}
async function saveTests(){save();if(currentUser)await ensureProfile();render();toast('Day 0 baseline saved')}
async function completeWorkout(){s.workout=true;s.burn+=+wb.value||0;save();if(currentUser){await supabaseClient.from('workout_logs').insert({user_id:currentUser.id,workout_date:today(),exercise:'Starter session',duration_minutes:+wm.value||0,estimated_calories:+wb.value||0,completed:true})}await sync();render();toast('Workout logged')}
function plan(){let rem=s.targets.cal-s.cal,rp=s.targets.p-s.p;let title=rp>35?'Protein-focused dinner':'Balanced next meal';let text=rp>35?'Try 4 chapathi + 4 medium chicken pieces + vegetables, adjusting portions to fit the remaining calories.':'Try 3–4 chapathi + chicken curry + vegetables, or a measured biryani portion with a protein-rich side.';document.getElementById('pt').textContent=title;document.getElementById('px').textContent=`${text} Remaining: ${Math.max(0,Math.round(rem))} kcal and ${Math.max(0,Math.round(rp))} g protein.`;go('food')}
function week(){if(s.daily.length<1)return toast('Keep logging daily data. The first full review is after 7 days.');let d=s.daily.slice(-7),ac=d.reduce((a,x)=>a+x.cal,0)/d.length,ap=d.reduce((a,x)=>a+x.p,0)/d.length,ab=d.reduce((a,x)=>a+x.burn,0),as=d.reduce((a,x)=>a+x.steps,0)/d.length;let w=(s.weights.at(-1)||68)-68;document.getElementById('analysis').textContent=`Last ${d.length} logged day(s): average intake ${Math.round(ac)} kcal/day, protein ${Math.round(ap)} g/day, estimated exercise burn ${Math.round(ab)} kcal total, average steps ${Math.round(as).toLocaleString()}. Weight change from 68 kg: ${w>=0?'+':''}${w.toFixed(1)} kg. ${d.length<7?'Continue until Day 7 before making a meaningful plan change.':'Use this trend to decide whether to keep or tweak calories/activity.'}`;go('progress')}
function resetApp(){if(confirm('Reset local app data? Cloud data is not deleted.')){localStorage.removeItem(localKey());location.reload()}}
function render(){document.getElementById('day').textContent='Day '+dayNum();let t=s.targets;cu.textContent=Math.round(s.cal);ct.textContent=t.cal;ps.textContent=`${Math.round(s.p)} / ${t.p} g`;fs.textContent=`${Math.round(s.f)} / ${t.f} g`;cs.textContent=`${Math.round(s.c)} / ${t.c} g`;cb.style.width=Math.min(100,s.cal/t.cal*100)+'%';rem.textContent=Math.max(0,Math.round(t.cal-s.cal)).toLocaleString()+' kcal';rp.textContent=Math.max(0,Math.round(t.p-s.p))+' g protein';rf.textContent=Math.max(0,Math.round(t.f-s.f))+' g fat';document.getElementById('steps').textContent=s.steps.toLocaleString();walk.textContent=Math.round(s.steps/100)+' min';cy.textContent=s.cycle+' min';burn.textContent=Math.round(s.burn)+' kcal';hw.textContent=(s.weights.at(-1)||68).toFixed(1);hb.textContent=s.measure.at(-1)?.b||97;hz.textContent=s.measure.at(-1)?.z||90;pb.textContent=s.tests.pull;let score=Math.round(Math.min(35,s.p/t.p*35)+Math.min(35,s.cal<=t.cal?35:t.cal/s.cal*35)+Math.min(15,s.steps/7000*15)+(s.workout?15:0));document.getElementById('score').textContent=score;coach.textContent=currentUser?`Cloud synced · Target ${t.cal} kcal · ${t.p} g protein.`:`Local mode · Sign in from ⚙️ to sync across devices.`;renderFoodList(document.getElementById('foodSearch')?.value||'');document.getElementById('log').innerHTML=s.meals.length?s.meals.map(x=>`<div class="meal"><span>${x[1]}<small>${x[3]} g protein · ${x[4]} g fat</small></span><b>${x[2]} kcal</b></div>`).join(''):'<div class="card">No meals logged today.</div>';document.getElementById('tests').innerHTML=TEST.map(t=>`<div class="test"><span class="exerciseName">${t[1]}<small>${t[2]}</small></span><strong class="target">${t[3]}</strong><div class="stepper"><button type="button" onclick="changeTest('${t[0]}',-1)">−</button><b id="v_${t[0]}">${s.tests[t[0]]}</b><button type="button" onclick="changeTest('${t[0]}',1)">+</button></div></div>`).join('');document.getElementById('measurements').innerHTML=s.measure.slice(-5).reverse().map(m=>`<div class="line" style="padding:8px 0"><span>Day ${m.day}</span><b>${m.w} kg · ${m.b} cm belly · ${m.z} cm waist</b></div>`).join('');document.getElementById('weightChart').textContent=s.weights.length>1?'Weight: '+s.weights.join(' → ')+' kg':'Add daily weights to see trend';document.getElementById('nutritionChart').innerHTML=s.daily.length?`Daily calories: ${s.daily.map(x=>x.cal).join(' · ')}<br>Protein: ${s.daily.map(x=>x.p).join(' · ')} g`:'Log daily data to see nutrition history.';document.getElementById('activityChart').innerHTML=s.daily.length?`Exercise burn: ${s.daily.map(x=>x.burn).join(' · ')} kcal<br>Steps: ${s.daily.map(x=>x.steps).join(' · ')}`:'Exercise calories will appear here.';document.getElementById('summary').textContent=`Age ${s.age} · Lightly active · ${t.cal} kcal`;document.getElementById('userDot').textContent=currentUser?'✓':'↗'}

render();
document.getElementById('foodSearch')?.addEventListener('input',e=>renderFoodList(e.target.value));
supabaseClient.auth.getSession().then(async({data})=>{currentUser=data.session?.user||null;loadLocal();if(currentUser){await loadCloud()}render()});
supabaseClient.auth.onAuthStateChange(async(_event,session)=>{currentUser=session?.user||null;if(currentUser){await ensureProfile();await loadCloud()}render()});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
