create table if not exists profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 age int default 29,
 height_cm numeric default 159,
 starting_weight_kg numeric default 68,
 activity_level text default 'lightly_active',
 calorie_target int default 1700,
 protein_target int default 120,
 fat_target int default 55,
 carb_target int default 185,
 created_at timestamptz default now()
);
create table if not exists daily_logs(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 date date not null,
 calories numeric default 0, protein numeric default 0, fat numeric default 0, carbs numeric default 0,
 exercise_calories numeric default 0, steps int default 0, walking_minutes int default 0, cycling_minutes int default 0,
 workout_completed boolean default false, weight_kg numeric,
 created_at timestamptz default now(),
 unique(user_id,date)
);
create table if not exists meals(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 date date not null,
 food_key text, food_name text not null, quantity numeric default 1, unit text default 'count',
 calories numeric default 0, protein numeric default 0, fat numeric default 0, carbs numeric default 0,
 created_at timestamptz default now()
);
create table if not exists foods(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 name text not null, calories_100g numeric not null, protein_100g numeric default 0, fat_100g numeric default 0, carbs_100g numeric default 0,
 source text, created_at timestamptz default now()
);
create table if not exists body_measurements(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 date date not null, weight_kg numeric, belly_cm numeric, waist_cm numeric, chest_cm numeric, biceps_cm numeric,
 created_at timestamptz default now()
);
alter table profiles enable row level security;
alter table daily_logs enable row level security;
alter table meals enable row level security;
alter table foods enable row level security;
alter table body_measurements enable row level security;
create policy "profiles own" on profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy "daily own" on daily_logs for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "meals own" on meals for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "foods own" on foods for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "measure own" on body_measurements for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
alter table profiles add column if not exists start_date date default current_date;
