-- V5.1 schema alignment
-- The V5 named-profile migration has already been run successfully.
-- No additional SQL is required for V5.1.
--
-- Actual database columns:
-- daily_logs.log_date
-- meals.daily_log_id
-- foods: name, serving_size, calories, protein, fat, carbs
-- body_measurements.measure_date
